=== Eanybing/jdbc-shards/src/main/resources/META-INF/ddal-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2014 suning.com Holding Ltd.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!ELEMENT ddal-config (settings?,schema,cluster,dataNodes?,tableRules?,ruleAlgorithms?)>

<!ELEMENT settings (property*)>

<!ELEMENT schema (tableGroup* , table*)>
<!ATTLIST schema 
name CDATA #REQUIRED
metadata CDATA #IMPLIED
>


<!ELEMENT cluster (shard+)>
<!ELEMENT shard (property*)>
<!ATTLIST shard 
name CDATA #REQUIRED
>


<!ELEMENT dataNodes (datasource+)>
<!ELEMENT datasource (property*)>
<!ATTLIST datasource 
id CDATA #REQUIRED
class CDATA #IMPLIED
jndi-name CDATA #IMPLIED
>

<!ELEMENT tableRules (tableRule+)>
<!ELEMENT tableRule (#PCDATA)>
<!ATTLIST tableRule 
resource CDATA #REQUIRED
>

<!ELEMENT ruleAlgorithms (ruleAlgorithm*)>
<!ELEMENT ruleAlgorithm (property*)>
<!ATTLIST ruleAlgorithm 
name CDATA #REQUIRED
class CDATA #REQUIRED
>

<!ELEMENT table (#PCDATA)>
<!ATTLIST table
name CDATA #REQUIRED
metadata CDATA #IMPLIED
router CDATA #IMPLIED
validation (true|false) #IMPLIED
scanLevel (unlimited|filter|anyIndex|uniqueIndex|shardingKey) #IMPLIED
broadcast CDATA #IMPLIED
>

<!ELEMENT tableGroup (table+)>
<!ATTLIST tableGroup
metadata CDATA #IMPLIED
router CDATA #IMPLIED
validation (true|false) #IMPLIED
scanLevel (unlimited|filter|anyIndex|uniqueIndex|shardingKey) #IMPLIED
broadcast CDATA #IMPLIED
>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property 
name CDATA #REQUIRED
value CDATA #REQUIRED
>

=== Eanybing/jdbc-shards/src/test/resources/config/ddal-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ddal-config PUBLIC "-//suning.com//DTD ddal-config//EN" "http://suning.com/dtd/ddal-config.dtd">
<ddal-config>

	<schema name="PUBLIC" metadata="shard1">
		<table name="t_student" metadata="shard1.t_student_001" router="partition4_with_id_mod"/>
		<table name="t_student_course" metadata="shard1.t_student_course_001" router="partition4_with_id_mod"/>
		<table name="t_school"/>
	</schema>

	<cluster>
		<shard name="shard1">
			<property name="description" value="db1m" />
		</shard>
		<shard name="shard2">
			<property name="description" value="db2m" />
		</shard>
		<shard name="shard3">
			<property name="description" value="db3m" />
		</shard>
		<shard name="shard4">
			<property name="description" value="db4m" />
		</shard>
	</cluster>


	<dataNodes>
		<datasource id="db1m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.76:3306/ddal_test1" />
			<property name="username" value="user" />
			<property name="password" value="abc" />
		</datasource>
		<datasource id="db1s" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.77:3306/ddal_test1" />
			<property name="username" value="user" />
			<property name="password" value="abc" />
		</datasource>
		<datasource id="db2m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.76:3306/ddal_test2" />
			<property name="username" value="user" />
			<property name="password" value="abc" />
		</datasource>
		<datasource id="db2s" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.77:3306/ddal_test2" />
			<property name="username" value="user" />
			<property name="password" value="abc" />
		</datasource>
		<datasource id="db3m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.76:3306/ddal_test3" />
			<property name="username" value="user" />
			<property name="password" value="abc" />
		</datasource>
		<datasource id="db3s" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.77:3306/ddal_test3" />
			<property name="username" value="user" />
			<property name="password" value="abc" />
		</datasource>
		<datasource id="db4m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.76:3306/ddal_test4" />
			<property name="username" value="user" />
			<property name="password" value="abc" />
		</datasource>
		<datasource id="db4s" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.77:3306/ddal_test4" />
			<property name="username" value="user" />
			<property name="password" value="abc" />
		</datasource>
	</dataNodes>
	
	
	<tableRules>
		<tableRule resource="/config/ddal-rule.xml"/>
	</tableRules>

</ddal-config>
